#!/bin/bash -x
#PBS -N sim_iter

#PBS -l walltime=00:30:00
#PBS -j oe

###source /public/software/profile.d/compiler_gnu-7.2.0.sh
###source /public/software/profile.d/mpi_openmpi-gnu-2.1.2.sh

source /public/software/profile.d/compiler_intel-compiler-2017.5.239.sh
source /public/software/profile.d/mpi_intelmpi-2017.4.239.sh

#running jobs
cd /public/home/yeyj/jacobi1

#PBS -l nodes=2:ppn=64
mpirun -np 64 ./test

exit 0
